language: generic
addons:
  apt:
    packages:
      - libc6:i386
      - libstdc++6:i386
env:
  global:
    - IDE_VERSION=1.8.5
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - arduino --pref "boardsmanager.additional.urls=https://mhv75.github.io/arduino-nRF5_ATCwatch/package_nRF5_ATCwatch_boards_index.json" --install-boards nrf5_ATCwatch:nRF5 > /dev/null
  - buildExampleSketch() { arduino --verbose-build --verify --board $1 $HOME/arduino-ide/examples/$2/$3/$3.ino; }
install:
  - mkdir -p $HOME/Arduino/hardware/nrf5_ATCwatch
  - ln -s $PWD $HOME/Arduino/hardware/nrf5_ATCwatch/nRF5
script:
  - buildExampleSketch nrf5_ATCwatch:nRF5:D6Emulator 1.DSD6
  - buildExampleSketch nrf5_ATCwatch:nRF5:HeartRateTest 1.DSD6
